// preload.js
const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
     saveSettings: (config) => ipcRenderer.invoke('save-settings', config),
     loadSettings: () => ipcRenderer.invoke('load-settings'),
     loadLearningConfig: () => ipcRenderer.invoke('load-learning-config'),
     getUsername: () => ipcRenderer.invoke('get-username'),
     resetSettings: () => ipcRenderer.invoke('reset-settings'),
     getOsSupport: () => ipcRenderer.invoke('get-os-support'),
     openOsSettings: (target) => ipcRenderer.invoke('open-os-settings', target),
     getPowerStatus: () => ipcRenderer.invoke('get-power-status'),
     listCameras: () => ipcRenderer.invoke('list-cameras'),
     listDisplays: () => ipcRenderer.invoke('list-displays'),
     getBrightnessBackend: () => ipcRenderer.invoke('get-brightness-backend'),
     openLogsFolder: () => ipcRenderer.invoke('open-logs-folder'),
     openSettingsFile: () => ipcRenderer.invoke('open-settings-file'),
     getActivities: () => ipcRenderer.invoke('activities:get'),
     setActivities: (raw) => ipcRenderer.invoke('activities:set', raw),
     addActivity: (a) => ipcRenderer.invoke('activity:add', a),
     updateActivity: (id, patch) => ipcRenderer.invoke('activity:update', { id, patch }),
     deleteActivity: (id) => ipcRenderer.invoke('activity:delete', id),
     checkActivityWindow: () => ipcRenderer.invoke('activity:check-window'),
     getVersion: () => ipcRenderer.invoke('about:get-version'),
     checkUpdatesNow: () => ipcRenderer.invoke('about:check-updates'),
     exportData: () => ipcRenderer.invoke('export-data'),
     importData: () => ipcRenderer.invoke('import-data'),
     windowControl: (action) => ipcRenderer.invoke('window-control', action),
     pauseAdjustments: (durationMs) => ipcRenderer.invoke('pause-adjustments', durationMs),
     resumeAdjustments: () => ipcRenderer.invoke('resume-adjustments'),
     getBrightnessHistory: (hours) => ipcRenderer.invoke('get-brightness-history', hours),
     clearLearningLogs: () => ipcRenderer.invoke('clear-learning-logs'),
     exportLogsCsv: () => ipcRenderer.invoke('export-logs-csv'),
     onWeatherUpdate: (callback) => ipcRenderer.on('weather-update', (_event, value) => callback(value)),
     onDynamicStatusUpdate: (callback) => ipcRenderer.on('dynamic-status-update', (_event, value) => callback(value)),
     onSettingsUpdated: (callback) => ipcRenderer.on('settings-updated', (_event, data) => callback(data)),
     onLogUpdate: (callback) => ipcRenderer.on('log-update', (_event, value) => callback(value)),
     onUpdateAvailable: (callback) => ipcRenderer.on('update-available', (_event, data) => callback(data)),
     onOsSupportUpdate: (callback) => ipcRenderer.on('os-support-update', (_event, data) => callback(data)),
     openExternal: (url) => ipcRenderer.invoke('open-external', url)
});